services:
  decap-oauth:
    image: ramank775/netlify-cms-github-oauth-provider:v1.1.0
    environment:
      NODE_ENV: "production"
      ORIGINS: "https://logicnest.biz,https://www.logicnest.biz"
      OAUTH_CLIENT_ID: "Ov23li5yzDQpR1LaMJ2G"
      OAUTH_CLIENT_SECRET: "503b3fbe67105dfa6bcf316d351a2e302e9a9329"
      REDIRECT_URL: "https://cms-auth.logicnest.biz/callback"
      PORT: "3111"
    ports:
      - "127.0.0.1:8088:3111"
    restart: always
