services:
  decap-oauth:
    image: ghcr.io/vencax/netlify-cms-github-oauth-provider:latest
    environment:
      CLIENT_ID: "GITHUB_CLIENT_ID"           # ← CHANGE
      CLIENT_SECRET: "GITHUB_CLIENT_SECRET"   # ← CHANGE
      OAUTH_HOST: "https://cms-auth.YOUR_DOMAIN:4081"
      OAUTH_REDIRECT_URI: "https://cms-auth.YOUR_DOMAIN:4081/callback"
      ALLOWED_ORIGINS: "https://YOUR_DOMAIN"  # add www if needed: https://YOUR_DOMAIN,https://www.YOUR_DOMAIN
    ports:
      - "127.0.0.1:8088:8080"
    restart: always
