name: Build & Deploy (Astro)

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@6.0
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /home/<cp-user>/hotdogs/logicnest.biz/htdocs/    # ← CHANGE to your CloudPanel docroot
          remote_host: <your.server.ip.or.hostname>                      # ← CHANGE
          remote_user: <cp-user>                                         # ← CHANGE
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
